# Generated by Django 6.0.3 on 2026-04-10 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_token_blacklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accent_color', models.CharField(default='#A3E635', max_length=7)),
                ('banner_preset', models.CharField(default='nebula', max_length=20)),
                ('banner_image', models.BinaryField(blank=True, null=True)),
                ('banner_image_content_type', models.CharField(blank=True, max_length=20, null=True)),
                ('pattern', models.CharField(choices=[('none', 'None'), ('grid', 'Grid'), ('dots', 'Dots'), ('lines', 'Lines'), ('cross', 'Cross')], default='none', max_length=10)),
                ('font', models.CharField(default='JetBrains Mono', max_length=30)),
                ('banner_opacity', models.IntegerField(default=100)),
                ('glow_intensity', models.IntegerField(default=25)),
                ('border_accent', models.IntegerField(default=0)),
                ('mood', models.CharField(choices=[('online', '// ONLINE'), ('coding', '// CODING'), ('afk', '// AFK'), ('creating', '// CREATING'), ('lurking', '// LURKING'), ('vibing', '// VIBING')], default='online', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_theme', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile_themes',
            },
        ),
    ]
